// Emits literal token values for the two places a CSS custom property cannot
// reach: a media query prelude and a Sass loop. `@media (min-width: var(--x))`
// is invalid in every engine, and `@for $i from 1 through var(--x)` has no
// meaning at compile time — so the breakpoints and the column counts have to be
// baked in. Every other token keeps going through `token()`, which resolves to
// a `var()` and therefore still follows `data-brand` at runtime.
//
// The trade this records: a brand can restyle the grid live through
// `data-brand`, but changing its breakpoints or its column counts means
// compiling the CSS from source against its own token file.

const SCSS_HEADER = `////
/// Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
////
/// Literal token values, for media query preludes and Sass loops only.
/// Anything that lands in a property value belongs in \`token()\` instead, so it
/// stays brand-switchable at runtime.

@use "sass:map";
`;

const SCSS_FUNCTION = `@function static-token($tokenName) {
  @if not map.has-key($__static-token-values, $tokenName) {
    @error 'No static token named "#{$tokenName}"';
  }

  @return map.get($__static-token-values, $tokenName);
}`;

export default function pluginStaticValues({
  scssFilename = 'letsui.tokens.static.scss',
  jsonFilename = 'letsui.tokens.static.json',
  include = [],
} = {}) {
  return {
    name: 'lets-ui/static-values',
    enforce: 'post',

    async build({ getTransforms, outputFile }) {
      const values = new Map();

      for (const id of include) {
        for (const transform of getTransforms({ format: 'css', id, mode: '.' })) {
          values.set(transform.id, transform.value);
        }
      }

      const entries = [...values].sort(([a], [b]) => a.localeCompare(b));

      if (entries.length === 0) {
        throw new Error(
          `[lets-ui/static-values] no tokens matched: ${include.join(', ')}`
        );
      }

      const map = entries
        .map(([id, value]) => `  "${id}": ${value},`)
        .join('\n');

      outputFile(
        scssFilename,
        `${SCSS_HEADER}\n$__static-token-values: (\n${map}\n);\n\n${SCSS_FUNCTION}\n`
      );

      outputFile(
        jsonFilename,
        `${JSON.stringify(Object.fromEntries(entries), null, 2)}\n`
      );
    },
  };
}
